<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1494441470420" stop="1494441472735">
	<name>Verify User Email</name>
	<title>Verify User Email</title>
	<test-cases>
		<test-case start="1494441470420" stop="1494441472733" status="failed">
			<name>checking user email is same</name>
			<title>checking user email is same</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="ec14988c-b431-46e8-aa54-ca0bdf3f52d2-attachment.png" type="image/png" size="76509"/>
			</attachments>
			<failure>
				<message>Expected &apos;umukka@gmail.com&apos; to equal undefined.</message>
				<stack-trace>Error: Failed expectation
    at /Users/zac01/Documents/protractor/myswaastherp/Complete_Profile/complete-profile.js:21:26
    at elementArrayFinder_.then (/usr/local/lib/node_modules/protractor/lib/element.ts:840:22)
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>