<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1495808837379" stop="1495808838615">
	<name>Verification URL</name>
	<title>Verification URL</title>
	<test-cases>
		<test-case start="1495808837379" stop="1495808838615" status="failed">
			<name>will verify the URL of verification page</name>
			<title>will verify the URL of verification page</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="d25b6e2d-60ab-4c24-99c7-ba72553976e9-attachment.png" type="image/png" size="80404"/>
			</attachments>
			<failure>
				<message>Expected &apos;https://myswaastherp.sia.co.in/#/upload-documents&apos; to equal &apos;https://myswaastherp.sia.co.in/#/verification&apos;.</message>
				<stack-trace>Error: Failed expectation
    at verificationHeading.verifyURL (/Users/zac01/Documents/protractor/myswaastherp/VerificationPage/verificationpage.js:11:41)
    at Object.it (/Users/zac01/Documents/protractor/myswaastherp/Specs/signup-success.spec.js:344:27)
    at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
    at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
    at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>